### ISSUE TITLE
Terminating app due to uncaught exception 'NameError'

### ISSUE THREAD

**Issue by eddanger** [andrewhavens/moticons#1]
Hi,

I am trying your gem for a tab bar item. I am getting this error:

```
icon_image(:ion, :star, size: 30, color: UIColor.blackColor)
```

```
        from delegate_module.rb:16:in `application:didFinishLaunchingWithOptions:'
2015-09-02 13:14:47.403 attendease-mobile[10054:1286343] *** Terminating app due to uncaught exception 'NameError', reason: 'icon.rb:40:in `create_instance': uninitialized constant Kernel::FAKIonIcons
 (NameError)
        from icon.rb:24:in `initialize:'
        from icon.rb:61:in `icon_image:'
        from hello_screen.rb:6:in `on_init'
```

**Comment by eddanger** [comment]
Actually after running `rake pod:install` it was fixed.

Awesome gem!

**Comment by andrewhavens** [comment]
Thanks! Glad you got it working. Sorry, I should have mentioned that in the readme. I'll make sure to add that.
